<?php

namespace Modules\Dashboard\Services;

use App\Helpers\Utils;
use App\Services\BaseService;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Modules\Dashboard\Models\Country;
use Modules\Dashboard\Models\Province;
use Modules\Dashboard\Repositories\ProvinceRepository;

/**
 * @extends BaseService<Province, ProvinceRepository>
 */
class ProvinceService extends BaseService
{
    public function __construct(
        ProvinceRepository $repository
    ) {
        parent::__construct($repository);
    }

    /**
     * @param  array<string, mixed>  $filters
     * @return LengthAwarePaginator<int, Province>|Collection<int, Province>
     */
    public function getProvinces(array $filters = [], bool $paginate = true): LengthAwarePaginator|Collection
    {
        $this->repository
            ->filtered($filters)
            ->orderBy(
                Country::select('name')
                    ->whereColumn('countries.id', 'provinces.country_id')
            )
            ->orderBy('name')
            ->withRelations();

        return $paginate ? $this->repository->paginate() : $this->repository->all();
    }

    public function create(array $data): Province
    {
        $data['slug'] ??= Utils::generateUniqueSlug($data['name'], Province::class);

        return parent::create($data);
    }

    protected function interpretData(array $data): array
    {
        $countryService = resolve(CountryService::class);
        if (isset($data['country'])) {
            /** @var Country $country */
            $country = $countryService->findByKey($data['country']);
            $data['country_id'] = $country->id;
        }

        return parent::interpretData($data); // TODO: Change the autogenerated stub
    }
}
