<?php

namespace Modules\Inventory\Providers;

use App\Providers\BaseModuleServiceProvider;
use Livewire\Livewire;
use Modules\Inventory\Livewire\WarehouseItems\WarehouseItemPicker;
use Modules\Inventory\Livewire\Warehouses\WarehousePicker;

class InventoryServiceProvider extends BaseModuleServiceProvider
{
    /**
     * The name of the module.
     */
    protected string $name = 'Inventory';

    /**
     * The lowercase version of the module name.
     */
    protected string $nameLower = 'inventory';

    /**
     * Command classes to register.
     *
     * @var string[]
     */
    // protected array $commands = [];

    /**
     * Provider classes to register.
     *
     * @var string[]
     */
    protected array $providers = [
        EventServiceProvider::class,
        RouteServiceProvider::class,
    ];

    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Livewire::component('inventory-warehouse-picker', WarehousePicker::class);
        Livewire::component('inventory-warehouse-item-picker', WarehouseItemPicker::class);
    }
}
