<?php

namespace App\Providers;

use Carbon\CarbonImmutable;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Rules\Password;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->configureDefaults();

        Blueprint::macro('slug', function (
            string $column = 'slug',
            int $length = 255,
            bool $hasSoftDelete = true
        ) {
            /** @var Blueprint $this */
            $this->string($column, $length);
            if ($hasSoftDelete) {
                $this->unique($column, 'deleted_at');
            }

            return $this;
        });

    }

    protected function loadTranslationsFrom($path, $namespace = null)
    {
        parent::loadTranslationsFrom($path, $namespace); // TODO: Change the autogenerated stub
    }

    /**
     * Configure default behaviors for production-ready applications.
     */
    protected function configureDefaults(): void
    {
        Date::use(CarbonImmutable::class);

        DB::prohibitDestructiveCommands(
            app()->isProduction(),
        );

        Password::defaults(fn (): ?Password => app()->isProduction()
            ? Password::min(12)
                ->mixedCase()
                ->letters()
                ->numbers()
                ->symbols()
                ->uncompromised()
            : null,
        );
    }
}
