<?php

namespace Modules\Dashboard\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Dashboard\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'افغانستان', 'code' => 'AF', 'code3' => 'AFG', 'phone_code' => '+93', 'is_active' => false],
            ['name' => 'آلبانی', 'code' => 'AL', 'code3' => 'ALB', 'phone_code' => '+355', 'is_active' => false],
            ['name' => 'الجزایر', 'code' => 'DZ', 'code3' => 'DZA', 'phone_code' => '+213', 'is_active' => false],
            ['name' => 'آندورا', 'code' => 'AD', 'code3' => 'AND', 'phone_code' => '+376', 'is_active' => false],
            ['name' => 'آنگولا', 'code' => 'AO', 'code3' => 'AGO', 'phone_code' => '+244', 'is_active' => false],
            ['name' => 'آنتیگوا و باربودا', 'code' => 'AG', 'code3' => 'ATG', 'phone_code' => '+1-268', 'is_active' => false],
            ['name' => 'آرژانتین', 'code' => 'AR', 'code3' => 'ARG', 'phone_code' => '+54', 'is_active' => false],
            ['name' => 'ارمنستان', 'code' => 'AM', 'code3' => 'ARM', 'phone_code' => '+374', 'is_active' => false],
            ['name' => 'استرالیا', 'code' => 'AU', 'code3' => 'AUS', 'phone_code' => '+61', 'is_active' => false],
            ['name' => 'اتریش', 'code' => 'AT', 'code3' => 'AUT', 'phone_code' => '+43', 'is_active' => false],
            ['name' => 'آذربایجان', 'code' => 'AZ', 'code3' => 'AZE', 'phone_code' => '+994', 'is_active' => false],
            ['name' => 'باهاما', 'code' => 'BS', 'code3' => 'BHS', 'phone_code' => '+1-242', 'is_active' => false],
            ['name' => 'بحرین', 'code' => 'BH', 'code3' => 'BHR', 'phone_code' => '+973', 'is_active' => false],
            ['name' => 'بنگلادش', 'code' => 'BD', 'code3' => 'BGD', 'phone_code' => '+880', 'is_active' => false],
            ['name' => 'باربادوس', 'code' => 'BB', 'code3' => 'BRB', 'phone_code' => '+1-246', 'is_active' => false],
            ['name' => 'بلاروس', 'code' => 'BY', 'code3' => 'BLR', 'phone_code' => '+375', 'is_active' => false],
            ['name' => 'بلژیک', 'code' => 'BE', 'code3' => 'BEL', 'phone_code' => '+32', 'is_active' => false],
            ['name' => 'بلیز', 'code' => 'BZ', 'code3' => 'BLZ', 'phone_code' => '+501', 'is_active' => false],
            ['name' => 'بنین', 'code' => 'BJ', 'code3' => 'BEN', 'phone_code' => '+229', 'is_active' => false],
            ['name' => 'بوتان', 'code' => 'BT', 'code3' => 'BTN', 'phone_code' => '+975', 'is_active' => false],
            ['name' => 'بولیوی', 'code' => 'BO', 'code3' => 'BOL', 'phone_code' => '+591', 'is_active' => false],
            ['name' => 'بوسنی و هرزگوین', 'code' => 'BA', 'code3' => 'BIH', 'phone_code' => '+387', 'is_active' => false],
            ['name' => 'بوتسوانا', 'code' => 'BW', 'code3' => 'BWA', 'phone_code' => '+267', 'is_active' => false],
            ['name' => 'برزیل', 'code' => 'BR', 'code3' => 'BRA', 'phone_code' => '+55', 'is_active' => false],
            ['name' => 'برونئی', 'code' => 'BN', 'code3' => 'BRN', 'phone_code' => '+673', 'is_active' => false],
            ['name' => 'بلغارستان', 'code' => 'BG', 'code3' => 'BGR', 'phone_code' => '+359', 'is_active' => false],
            ['name' => 'بورکینافاسو', 'code' => 'BF', 'code3' => 'BFA', 'phone_code' => '+226', 'is_active' => false],
            ['name' => 'بوروندی', 'code' => 'BI', 'code3' => 'BDI', 'phone_code' => '+257', 'is_active' => false],
            ['name' => 'کیپ ورد', 'code' => 'CV', 'code3' => 'CPV', 'phone_code' => '+238', 'is_active' => false],
            ['name' => 'کامبوج', 'code' => 'KH', 'code3' => 'KHM', 'phone_code' => '+855', 'is_active' => false],
            ['name' => 'کامرون', 'code' => 'CM', 'code3' => 'CMR', 'phone_code' => '+237', 'is_active' => false],
            ['name' => 'کانادا', 'code' => 'CA', 'code3' => 'CAN', 'phone_code' => '+1', 'is_active' => false],
            ['name' => 'جمهوری آفریقای مرکزی', 'code' => 'CF', 'code3' => 'CAF', 'phone_code' => '+236', 'is_active' => false],
            ['name' => 'چاد', 'code' => 'TD', 'code3' => 'TCD', 'phone_code' => '+235', 'is_active' => false],
            ['name' => 'شیلی', 'code' => 'CL', 'code3' => 'CHL', 'phone_code' => '+56', 'is_active' => false],
            ['name' => 'چین', 'code' => 'CN', 'code3' => 'CHN', 'phone_code' => '+86', 'is_active' => false],
            ['name' => 'کلمبیا', 'code' => 'CO', 'code3' => 'COL', 'phone_code' => '+57', 'is_active' => false],
            ['name' => 'کومور', 'code' => 'KM', 'code3' => 'COM', 'phone_code' => '+269', 'is_active' => false],
            ['name' => 'جمهوری کنگو', 'code' => 'CG', 'code3' => 'COG', 'phone_code' => '+242', 'is_active' => false],
            ['name' => 'جمهوری دموکراتیک کنگو', 'code' => 'CD', 'code3' => 'COD', 'phone_code' => '+243', 'is_active' => false],
            ['name' => 'کاستاریکا', 'code' => 'CR', 'code3' => 'CRI', 'phone_code' => '+506', 'is_active' => false],
            ['name' => 'ساحل عاج', 'code' => 'CI', 'code3' => 'CIV', 'phone_code' => '+225', 'is_active' => false],
            ['name' => 'کرواسی', 'code' => 'HR', 'code3' => 'HRV', 'phone_code' => '+385', 'is_active' => false],
            ['name' => 'کوبا', 'code' => 'CU', 'code3' => 'CUB', 'phone_code' => '+53', 'is_active' => false],
            ['name' => 'قبرس', 'code' => 'CY', 'code3' => 'CYP', 'phone_code' => '+357', 'is_active' => false],
            ['name' => 'جمهوری چک', 'code' => 'CZ', 'code3' => 'CZE', 'phone_code' => '+420', 'is_active' => false],
            ['name' => 'دانمارک', 'code' => 'DK', 'code3' => 'DNK', 'phone_code' => '+45', 'is_active' => false],
            ['name' => 'جیبوتی', 'code' => 'DJ', 'code3' => 'DJI', 'phone_code' => '+253', 'is_active' => false],
            ['name' => 'دومینیکا', 'code' => 'DM', 'code3' => 'DMA', 'phone_code' => '+1-767', 'is_active' => false],
            ['name' => 'جمهوری دومینیکن', 'code' => 'DO', 'code3' => 'DOM', 'phone_code' => '+1-809', 'is_active' => false],
            ['name' => 'اکوادور', 'code' => 'EC', 'code3' => 'ECU', 'phone_code' => '+593', 'is_active' => false],
            ['name' => 'مصر', 'code' => 'EG', 'code3' => 'EGY', 'phone_code' => '+20', 'is_active' => false],
            ['name' => 'السالوادور', 'code' => 'SV', 'code3' => 'SLV', 'phone_code' => '+503', 'is_active' => false],
            ['name' => 'گینه استوایی', 'code' => 'GQ', 'code3' => 'GNQ', 'phone_code' => '+240', 'is_active' => false],
            ['name' => 'اریتره', 'code' => 'ER', 'code3' => 'ERI', 'phone_code' => '+291', 'is_active' => false],
            ['name' => 'استونی', 'code' => 'EE', 'code3' => 'EST', 'phone_code' => '+372', 'is_active' => false],
            ['name' => 'اسواتینی', 'code' => 'SZ', 'code3' => 'SWZ', 'phone_code' => '+268', 'is_active' => false],
            ['name' => 'اتیوپی', 'code' => 'ET', 'code3' => 'ETH', 'phone_code' => '+251', 'is_active' => false],
            ['name' => 'فیجی', 'code' => 'FJ', 'code3' => 'FJI', 'phone_code' => '+679', 'is_active' => false],
            ['name' => 'فنلاند', 'code' => 'FI', 'code3' => 'FIN', 'phone_code' => '+358', 'is_active' => false],
            ['name' => 'فرانسه', 'code' => 'FR', 'code3' => 'FRA', 'phone_code' => '+33', 'is_active' => false],
            ['name' => 'گابن', 'code' => 'GA', 'code3' => 'GAB', 'phone_code' => '+241', 'is_active' => false],
            ['name' => 'گامبیا', 'code' => 'GM', 'code3' => 'GMB', 'phone_code' => '+220', 'is_active' => false],
            ['name' => 'گرجستان', 'code' => 'GE', 'code3' => 'GEO', 'phone_code' => '+995', 'is_active' => false],
            ['name' => 'آلمان', 'code' => 'DE', 'code3' => 'DEU', 'phone_code' => '+49', 'is_active' => false],
            ['name' => 'غنا', 'code' => 'GH', 'code3' => 'GHA', 'phone_code' => '+233', 'is_active' => false],
            ['name' => 'یونان', 'code' => 'GR', 'code3' => 'GRC', 'phone_code' => '+30', 'is_active' => false],
            ['name' => 'گرنادا', 'code' => 'GD', 'code3' => 'GRD', 'phone_code' => '+1-473', 'is_active' => false],
            ['name' => 'گواتمالا', 'code' => 'GT', 'code3' => 'GTM', 'phone_code' => '+502', 'is_active' => false],
            ['name' => 'گینه', 'code' => 'GN', 'code3' => 'GIN', 'phone_code' => '+224', 'is_active' => false],
            ['name' => 'گینه بیسائو', 'code' => 'GW', 'code3' => 'GNB', 'phone_code' => '+245', 'is_active' => false],
            ['name' => 'گویان', 'code' => 'GY', 'code3' => 'GUY', 'phone_code' => '+592', 'is_active' => false],
            ['name' => 'هائیتی', 'code' => 'HT', 'code3' => 'HTI', 'phone_code' => '+509', 'is_active' => false],
            ['name' => 'هندوراس', 'code' => 'HN', 'code3' => 'HND', 'phone_code' => '+504', 'is_active' => false],
            ['name' => 'مجارستان', 'code' => 'HU', 'code3' => 'HUN', 'phone_code' => '+36', 'is_active' => false],
            ['name' => 'ایسلند', 'code' => 'IS', 'code3' => 'ISL', 'phone_code' => '+354', 'is_active' => false],
            ['name' => 'هند', 'code' => 'IN', 'code3' => 'IND', 'phone_code' => '+91', 'is_active' => false],
            ['name' => 'اندونزی', 'code' => 'ID', 'code3' => 'IDN', 'phone_code' => '+62', 'is_active' => false],
            ['name' => 'ایران', 'code' => 'IR', 'code3' => 'IRN', 'phone_code' => '+98', 'is_active' => true],
            ['name' => 'عراق', 'code' => 'IQ', 'code3' => 'IRQ', 'phone_code' => '+964', 'is_active' => false],
            ['name' => 'ایرلند', 'code' => 'IE', 'code3' => 'IRL', 'phone_code' => '+353', 'is_active' => false],
            ['name' => 'اسرائیل', 'code' => 'IL', 'code3' => 'ISR', 'phone_code' => '+972', 'is_active' => false],
            ['name' => 'ایتالیا', 'code' => 'IT', 'code3' => 'ITA', 'phone_code' => '+39', 'is_active' => false],
            ['name' => 'جامائیکا', 'code' => 'JM', 'code3' => 'JAM', 'phone_code' => '+1-876', 'is_active' => false],
            ['name' => 'ژاپن', 'code' => 'JP', 'code3' => 'JPN', 'phone_code' => '+81', 'is_active' => false],
            ['name' => 'اردن', 'code' => 'JO', 'code3' => 'JOR', 'phone_code' => '+962', 'is_active' => false],
            ['name' => 'قزاقستان', 'code' => 'KZ', 'code3' => 'KAZ', 'phone_code' => '+7', 'is_active' => false],
            ['name' => 'کنیا', 'code' => 'KE', 'code3' => 'KEN', 'phone_code' => '+254', 'is_active' => false],
            ['name' => 'کیریباتی', 'code' => 'KI', 'code3' => 'KIR', 'phone_code' => '+686', 'is_active' => false],
            ['name' => 'کره شمالی', 'code' => 'KP', 'code3' => 'PRK', 'phone_code' => '+850', 'is_active' => false],
            ['name' => 'کره جنوبی', 'code' => 'KR', 'code3' => 'KOR', 'phone_code' => '+82', 'is_active' => false],
            ['name' => 'کویت', 'code' => 'KW', 'code3' => 'KWT', 'phone_code' => '+965', 'is_active' => false],
            ['name' => 'قرقیزستان', 'code' => 'KG', 'code3' => 'KGZ', 'phone_code' => '+996', 'is_active' => false],
            ['name' => 'لائوس', 'code' => 'LA', 'code3' => 'LAO', 'phone_code' => '+856', 'is_active' => false],
            ['name' => 'لتونی', 'code' => 'LV', 'code3' => 'LVA', 'phone_code' => '+371', 'is_active' => false],
            ['name' => 'لبنان', 'code' => 'LB', 'code3' => 'LBN', 'phone_code' => '+961', 'is_active' => false],
            ['name' => 'لسوتو', 'code' => 'LS', 'code3' => 'LSO', 'phone_code' => '+266', 'is_active' => false],
            ['name' => 'لیبریا', 'code' => 'LR', 'code3' => 'LBR', 'phone_code' => '+231', 'is_active' => false],
            ['name' => 'لیبی', 'code' => 'LY', 'code3' => 'LBY', 'phone_code' => '+218', 'is_active' => false],
            ['name' => 'لیختن‌اشتاین', 'code' => 'LI', 'code3' => 'LIE', 'phone_code' => '+423', 'is_active' => false],
            ['name' => 'لیتوانی', 'code' => 'LT', 'code3' => 'LTU', 'phone_code' => '+370', 'is_active' => false],
            ['name' => 'لوکزامبورگ', 'code' => 'LU', 'code3' => 'LUX', 'phone_code' => '+352', 'is_active' => false],
            ['name' => 'ماداگاسکار', 'code' => 'MG', 'code3' => 'MDG', 'phone_code' => '+261', 'is_active' => false],
            ['name' => 'مالاوی', 'code' => 'MW', 'code3' => 'MWI', 'phone_code' => '+265', 'is_active' => false],
            ['name' => 'مالزی', 'code' => 'MY', 'code3' => 'MYS', 'phone_code' => '+60', 'is_active' => false],
            ['name' => 'مالدیو', 'code' => 'MV', 'code3' => 'MDV', 'phone_code' => '+960', 'is_active' => false],
            ['name' => 'مالی', 'code' => 'ML', 'code3' => 'MLI', 'phone_code' => '+223', 'is_active' => false],
            ['name' => 'مالت', 'code' => 'MT', 'code3' => 'MLT', 'phone_code' => '+356', 'is_active' => false],
            ['name' => 'جزایر مارشال', 'code' => 'MH', 'code3' => 'MHL', 'phone_code' => '+692', 'is_active' => false],
            ['name' => 'موریتانی', 'code' => 'MR', 'code3' => 'MRT', 'phone_code' => '+222', 'is_active' => false],
            ['name' => 'موریس', 'code' => 'MU', 'code3' => 'MUS', 'phone_code' => '+230', 'is_active' => false],
            ['name' => 'مکزیک', 'code' => 'MX', 'code3' => 'MEX', 'phone_code' => '+52', 'is_active' => false],
            ['name' => 'میکرونزی', 'code' => 'FM', 'code3' => 'FSM', 'phone_code' => '+691', 'is_active' => false],
            ['name' => 'مولداوی', 'code' => 'MD', 'code3' => 'MDA', 'phone_code' => '+373', 'is_active' => false],
            ['name' => 'موناکو', 'code' => 'MC', 'code3' => 'MCO', 'phone_code' => '+377', 'is_active' => false],
            ['name' => 'مغولستان', 'code' => 'MN', 'code3' => 'MNG', 'phone_code' => '+976', 'is_active' => false],
            ['name' => 'مونته‌نگرو', 'code' => 'ME', 'code3' => 'MNE', 'phone_code' => '+382', 'is_active' => false],
            ['name' => 'مراکش', 'code' => 'MA', 'code3' => 'MAR', 'phone_code' => '+212', 'is_active' => false],
            ['name' => 'موزامبیک', 'code' => 'MZ', 'code3' => 'MOZ', 'phone_code' => '+258', 'is_active' => false],
            ['name' => 'میانمار', 'code' => 'MM', 'code3' => 'MMR', 'phone_code' => '+95', 'is_active' => false],
            ['name' => 'نامیبیا', 'code' => 'NA', 'code3' => 'NAM', 'phone_code' => '+264', 'is_active' => false],
            ['name' => 'نائورو', 'code' => 'NR', 'code3' => 'NRU', 'phone_code' => '+674', 'is_active' => false],
            ['name' => 'نپال', 'code' => 'NP', 'code3' => 'NPL', 'phone_code' => '+977', 'is_active' => false],
            ['name' => 'هلند', 'code' => 'NL', 'code3' => 'NLD', 'phone_code' => '+31', 'is_active' => false],
            ['name' => 'نیوزیلند', 'code' => 'NZ', 'code3' => 'NZL', 'phone_code' => '+64', 'is_active' => false],
            ['name' => 'نیکاراگوئه', 'code' => 'NI', 'code3' => 'NIC', 'phone_code' => '+505', 'is_active' => false],
            ['name' => 'نیجر', 'code' => 'NE', 'code3' => 'NER', 'phone_code' => '+227', 'is_active' => false],
            ['name' => 'نیجریه', 'code' => 'NG', 'code3' => 'NGA', 'phone_code' => '+234', 'is_active' => false],
            ['name' => 'مقدونیه شمالی', 'code' => 'MK', 'code3' => 'MKD', 'phone_code' => '+389', 'is_active' => false],
            ['name' => 'نروژ', 'code' => 'NO', 'code3' => 'NOR', 'phone_code' => '+47', 'is_active' => false],
            ['name' => 'عمان', 'code' => 'OM', 'code3' => 'OMN', 'phone_code' => '+968', 'is_active' => false],
            ['name' => 'پاکستان', 'code' => 'PK', 'code3' => 'PAK', 'phone_code' => '+92', 'is_active' => false],
            ['name' => 'پالائو', 'code' => 'PW', 'code3' => 'PLW', 'phone_code' => '+680', 'is_active' => false],
            ['name' => 'پاناما', 'code' => 'PA', 'code3' => 'PAN', 'phone_code' => '+507', 'is_active' => false],
            ['name' => 'پاپوآ گینه نو', 'code' => 'PG', 'code3' => 'PNG', 'phone_code' => '+675', 'is_active' => false],
            ['name' => 'پاراگوئه', 'code' => 'PY', 'code3' => 'PRY', 'phone_code' => '+595', 'is_active' => false],
            ['name' => 'پرو', 'code' => 'PE', 'code3' => 'PER', 'phone_code' => '+51', 'is_active' => false],
            ['name' => 'فیلیپین', 'code' => 'PH', 'code3' => 'PHL', 'phone_code' => '+63', 'is_active' => false],
            ['name' => 'لهستان', 'code' => 'PL', 'code3' => 'POL', 'phone_code' => '+48', 'is_active' => false],
            ['name' => 'پرتغال', 'code' => 'PT', 'code3' => 'PRT', 'phone_code' => '+351', 'is_active' => false],
            ['name' => 'قطر', 'code' => 'QA', 'code3' => 'QAT', 'phone_code' => '+974', 'is_active' => false],
            ['name' => 'رومانی', 'code' => 'RO', 'code3' => 'ROU', 'phone_code' => '+40', 'is_active' => false],
            ['name' => 'روسیه', 'code' => 'RU', 'code3' => 'RUS', 'phone_code' => '+7', 'is_active' => false],
            ['name' => 'رواندا', 'code' => 'RW', 'code3' => 'RWA', 'phone_code' => '+250', 'is_active' => false],
            ['name' => 'سنت کیتس و نویس', 'code' => 'KN', 'code3' => 'KNA', 'phone_code' => '+1-869', 'is_active' => false],
            ['name' => 'سنت لوسیا', 'code' => 'LC', 'code3' => 'LCA', 'phone_code' => '+1-758', 'is_active' => false],
            ['name' => 'سنت وینسنت و گرنادین‌ها', 'code' => 'VC', 'code3' => 'VCT', 'phone_code' => '+1-784', 'is_active' => false],
            ['name' => 'ساموآ', 'code' => 'WS', 'code3' => 'WSM', 'phone_code' => '+685', 'is_active' => false],
            ['name' => 'سن مارینو', 'code' => 'SM', 'code3' => 'SMR', 'phone_code' => '+378', 'is_active' => false],
            ['name' => 'سائوتومه و پرنسیپ', 'code' => 'ST', 'code3' => 'STP', 'phone_code' => '+239', 'is_active' => false],
            ['name' => 'عربستان سعودی', 'code' => 'SA', 'code3' => 'SAU', 'phone_code' => '+966', 'is_active' => false],
            ['name' => 'سنگال', 'code' => 'SN', 'code3' => 'SEN', 'phone_code' => '+221', 'is_active' => false],
            ['name' => 'صربستان', 'code' => 'RS', 'code3' => 'SRB', 'phone_code' => '+381', 'is_active' => false],
            ['name' => 'سیشل', 'code' => 'SC', 'code3' => 'SYC', 'phone_code' => '+248', 'is_active' => false],
            ['name' => 'سیرالئون', 'code' => 'SL', 'code3' => 'SLE', 'phone_code' => '+232', 'is_active' => false],
            ['name' => 'سنگاپور', 'code' => 'SG', 'code3' => 'SGP', 'phone_code' => '+65', 'is_active' => false],
            ['name' => 'اسلواکی', 'code' => 'SK', 'code3' => 'SVK', 'phone_code' => '+421', 'is_active' => false],
            ['name' => 'اسلوونی', 'code' => 'SI', 'code3' => 'SVN', 'phone_code' => '+386', 'is_active' => false],
            ['name' => 'جزایر سلیمان', 'code' => 'SB', 'code3' => 'SLB', 'phone_code' => '+677', 'is_active' => false],
            ['name' => 'سومالی', 'code' => 'SO', 'code3' => 'SOM', 'phone_code' => '+252', 'is_active' => false],
            ['name' => 'آفریقای جنوبی', 'code' => 'ZA', 'code3' => 'ZAF', 'phone_code' => '+27', 'is_active' => false],
            ['name' => 'سودان جنوبی', 'code' => 'SS', 'code3' => 'SSD', 'phone_code' => '+211', 'is_active' => false],
            ['name' => 'اسپانیا', 'code' => 'ES', 'code3' => 'ESP', 'phone_code' => '+34', 'is_active' => false],
            ['name' => 'سری‌لانکا', 'code' => 'LK', 'code3' => 'LKA', 'phone_code' => '+94', 'is_active' => false],
            ['name' => 'سودان', 'code' => 'SD', 'code3' => 'SDN', 'phone_code' => '+249', 'is_active' => false],
            ['name' => 'سورینام', 'code' => 'SR', 'code3' => 'SUR', 'phone_code' => '+597', 'is_active' => false],
            ['name' => 'سوئد', 'code' => 'SE', 'code3' => 'SWE', 'phone_code' => '+46', 'is_active' => false],
            ['name' => 'سوئیس', 'code' => 'CH', 'code3' => 'CHE', 'phone_code' => '+41', 'is_active' => false],
            ['name' => 'سوریه', 'code' => 'SY', 'code3' => 'SYR', 'phone_code' => '+963', 'is_active' => false],
            ['name' => 'تاجیکستان', 'code' => 'TJ', 'code3' => 'TJK', 'phone_code' => '+992', 'is_active' => false],
            ['name' => 'تانزانیا', 'code' => 'TZ', 'code3' => 'TZA', 'phone_code' => '+255', 'is_active' => false],
            ['name' => 'تایلند', 'code' => 'TH', 'code3' => 'THA', 'phone_code' => '+66', 'is_active' => false],
            ['name' => 'تیمور شرقی', 'code' => 'TL', 'code3' => 'TLS', 'phone_code' => '+670', 'is_active' => false],
            ['name' => 'توگو', 'code' => 'TG', 'code3' => 'TGO', 'phone_code' => '+228', 'is_active' => false],
            ['name' => 'تونگا', 'code' => 'TO', 'code3' => 'TON', 'phone_code' => '+676', 'is_active' => false],
            ['name' => 'ترینیداد و توباگو', 'code' => 'TT', 'code3' => 'TTO', 'phone_code' => '+1-868', 'is_active' => false],
            ['name' => 'تونس', 'code' => 'TN', 'code3' => 'TUN', 'phone_code' => '+216', 'is_active' => false],
            ['name' => 'ترکیه', 'code' => 'TR', 'code3' => 'TUR', 'phone_code' => '+90', 'is_active' => false],
            ['name' => 'ترکمنستان', 'code' => 'TM', 'code3' => 'TKM', 'phone_code' => '+993', 'is_active' => false],
            ['name' => 'تووالو', 'code' => 'TV', 'code3' => 'TUV', 'phone_code' => '+688', 'is_active' => false],
            ['name' => 'اوگاندا', 'code' => 'UG', 'code3' => 'UGA', 'phone_code' => '+256', 'is_active' => false],
            ['name' => 'اوکراین', 'code' => 'UA', 'code3' => 'UKR', 'phone_code' => '+380', 'is_active' => false],
            ['name' => 'امارات متحده عربی', 'code' => 'AE', 'code3' => 'ARE', 'phone_code' => '+971', 'is_active' => false],
            ['name' => 'بریتانیا', 'code' => 'GB', 'code3' => 'GBR', 'phone_code' => '+44', 'is_active' => false],
            ['name' => 'ایالات متحده آمریکا', 'code' => 'US', 'code3' => 'USA', 'phone_code' => '+1', 'is_active' => false],
            ['name' => 'اروگوئه', 'code' => 'UY', 'code3' => 'URY', 'phone_code' => '+598', 'is_active' => false],
            ['name' => 'ازبکستان', 'code' => 'UZ', 'code3' => 'UZB', 'phone_code' => '+998', 'is_active' => false],
            ['name' => 'وانواتو', 'code' => 'VU', 'code3' => 'VUT', 'phone_code' => '+678', 'is_active' => false],
            ['name' => 'واتیکان', 'code' => 'VA', 'code3' => 'VAT', 'phone_code' => '+379', 'is_active' => false],
            ['name' => 'ونزوئلا', 'code' => 'VE', 'code3' => 'VEN', 'phone_code' => '+58', 'is_active' => false],
            ['name' => 'ویتنام', 'code' => 'VN', 'code3' => 'VNM', 'phone_code' => '+84', 'is_active' => false],
            ['name' => 'یمن', 'code' => 'YE', 'code3' => 'YEM', 'phone_code' => '+967', 'is_active' => false],
            ['name' => 'زامبیا', 'code' => 'ZM', 'code3' => 'ZMB', 'phone_code' => '+260', 'is_active' => false],
            ['name' => 'زیمبابوه', 'code' => 'ZW', 'code3' => 'ZWE', 'phone_code' => '+263', 'is_active' => false],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }

    }
}
